### ISSUE TITLE
LogoImage component returns 404 error

### ISSUE THREAD

**Issue by junlee91** [CreativeSolutionLabs/careertalk-frontend#69]
### Description
Our logo provider, 'clearbit' does not have all company logos and returns 404 error for invalid company url request. We need a better error handlings and not show 404 errors in the console. 

![Screen Shot 2019-06-30 at 5 23 16 PM](https://user-images.githubusercontent.com/20062563/60402928-dd619580-9b5b-11e9-8748-5a1799b9805d.png)

### Additional Info
related code - https://github.com/CreativeSolutionLabs/careertalk-frontend/blob/master/src/Components/commons/LogoImage.jsx#L46-L54

**Comment by hmx789** [comment]
The 404 responses are coming from clearbit because clearbit was unsuccessful on finding an image for that specific company. Because these responses are coming from clearbit we will be unable to hide them. Right now these 404 errors trigger the error handler which then loads up the default company image. 

In the future, we can save the company logos to S3 and provide default images for those companys within S3 if there is no logo for them. This way we can get rid of the 404 responses from clearbit.
